FROM node:8.6
MAINTAINER Mahan Hazrati<eng.mahan.hazrati@gmail.com>

RUN ln -sf /usr/share/zoneinfo/Asia/Bangkok /etc/localtime

RUN apt-get update && apt-get -y upgrade

RUN apt-get -y install  build-essential \
                        git \
                        curl

RUN apt-get remove npm
RUN apt-get update
RUN apt-get install -y npm

RUN npm install -g pm2 yarn -s

ENV TMP_DIR=/tmp
ENV PROD_DIR=/opt/app

RUN mkdir -p $TMP_DIR
COPY yarn.lock $TMP_DIR/yarn.lock
COPY package.json $TMP_DIR/package.json
RUN cd $TMP_DIR && yarn

COPY $TMP_DIR $PROD_DIR
COPY . $PROD_DIR/
COPY ./.env.kube.test $PROD_DIR/.env.test

WORKDIR $PROD_DIR

CMD yarn && \
	pm2 start pm2.test.config.js --no-daemon

EXPOSE 80
